// Compile the same execution core as desktop without linking Tauri.
#[path = "../../src-tauri/src/agent.rs"]
pub mod agent;
#[path = "../../src-tauri/src/asr_stream.rs"]
pub mod asr_stream;
pub mod daemon;
#[path = "../../src-tauri/src/deviceauth.rs"]
pub mod deviceauth;
#[path = "../../src-tauri/src/event_sink.rs"]
pub mod event_sink;
#[path = "../../src-tauri/src/graph.rs"]
pub mod graph;
#[path = "../../src-tauri/src/graph_custody.rs"]
pub mod graph_custody;
#[path = "../../src-tauri/src/hardware.rs"]
pub mod hardware;
#[path = "../../src-tauri/src/mererun.rs"]
pub mod mererun;
#[path = "../../src-tauri/src/model_plan.rs"]
pub mod model_plan;
#[path = "../../src-tauri/src/native_video.rs"]
pub mod native_video;
#[path = "../../src-tauri/src/plugins.rs"]
pub mod plugins;
#[path = "../../src-tauri/src/process_activity.rs"]
pub mod process_activity;
#[path = "../../src-tauri/src/protocol.rs"]
pub mod protocol;
#[path = "../../src-tauri/src/resident_video.rs"]
pub mod resident_video;
#[path = "../../src-tauri/src/runtime_binary.rs"]
pub mod runtime_binary;
#[path = "../../src-tauri/src/work_gate.rs"]
pub mod work_gate;
