import type { RelayContext } from './relay-context';
import type { RelayRouteHandlers } from './relay-routing';
import {
  handleResult,
  handleTalkResponse,
  handleTalkError,
  handleAsrResponse,
  handleAsrError,
  handleEmbedResponse,
  handleEmbedError,
  handleOcrResponse,
  handleOcrError,
  handleToolResult,
  handleToolError,
} from './relay-agent';
import { acceptAgentWebSocket, handleStatus } from './relay-api-status';
import {
  handleSubmitJob,
  handleDeleteJobImage,
  handleGetJob,
  handleCancelJob,
  handleImageUpload,
} from './relay-api-jobs';
import {
  handleSubmitChat,
  handleGetChat,
  handleCancelChat,
} from './relay-api-chat';
import {
  handleSubmitTalk,
  handleGetTalk,
  handleCancelTalk,
  handleDeleteTalkAudio,
  handleAudioUpload,
} from './relay-api-talk';
import {
  handleSubmitAsr,
  handleGetAsr,
  handleCancelAsr,
  handleSubmitEmbed,
  handleGetEmbed,
  handleCancelEmbed,
  handleSubmitOcr,
  handleGetOcr,
  handleCancelOcr,
} from './relay-api-analysis';
import {
  handleSubmitTool,
  handleGetTool,
  handleCancelTool,
  handleToolUpload,
} from './relay-api-tools';
import {
  handleFleetSnapshot,
  handleApplyFleetModelPlan,
  handleCancelFleetModelPlan,
  handleCreateFleetModelPlan,
  handleGetFleetModelPlan,
  handleListFleetModelPlans,
  handleRefreshFleetNode,
  handleUpdateFleetNode,
  handleUpdateFleetSettings,
} from './relay-api-fleet';
import {
  graphFleetCapabilities,
  handleCancelGraphJob,
  handleCommitGraphJob,
  handleCreateGraphJob,
  handleGetGraphArtifact,
  handleGetGraphJob,
  handleGetGraphRunManifest,
  handleGraphError,
  handleGraphEvent,
  handleGraphEvents,
  handleGraphNodeRequest,
  handleGraphTelemetry,
  handleGraphResult,
  handleListGraphJobs,
  handlePreflightGraphJob,
  handleRetryGraphJob,
  handleUploadGraphAsset,
} from './relay-api-graph';

export function createRelayRouteHandlers(ctx: RelayContext): RelayRouteHandlers {
  return {
    acceptAgentWebSocket: (request: Request) => acceptAgentWebSocket(ctx, request),
    getRequestUserId: (request: Request) => ctx.getRequestUserId(request),
    handleStatus: () => handleStatus(ctx),
    handleFleetSnapshot: () => handleFleetSnapshot(ctx),
    handleUpdateFleetSettings: (request: Request) => handleUpdateFleetSettings(ctx, request),
    handleUpdateFleetNode: (deviceId: string, request: Request) =>
      handleUpdateFleetNode(ctx, deviceId, request),
    handleRefreshFleetNode: (deviceId: string) => handleRefreshFleetNode(ctx, deviceId),
    handleCreateFleetModelPlan: (request: Request) => handleCreateFleetModelPlan(ctx, request),
    handleListFleetModelPlans: (limit: number) => handleListFleetModelPlans(ctx, limit),
    handleGetFleetModelPlan: (planId: string) => handleGetFleetModelPlan(ctx, planId),
    handleApplyFleetModelPlan: (planId: string, request: Request) =>
      handleApplyFleetModelPlan(ctx, planId, request),
    handleCancelFleetModelPlan: (planId: string) => handleCancelFleetModelPlan(ctx, planId),
    handleResult: (msg) => handleResult(ctx, msg),
    handleTalkResponse: (msg) => handleTalkResponse(ctx, msg),
    handleTalkError: (msg) => handleTalkError(ctx, msg),
    handleAsrResponse: (msg) => handleAsrResponse(ctx, msg),
    handleAsrError: (msg) => handleAsrError(ctx, msg),
    handleEmbedResponse: (msg) => handleEmbedResponse(ctx, msg),
    handleEmbedError: (msg) => handleEmbedError(ctx, msg),
    handleOcrResponse: (msg) => handleOcrResponse(ctx, msg),
    handleOcrError: (msg) => handleOcrError(ctx, msg),
    handleToolResult: (msg) => handleToolResult(ctx, msg),
    handleToolError: (msg) => handleToolError(ctx, msg),
    handleSubmitJob: (request, userId) => handleSubmitJob(ctx, request, userId),
    handleDeleteJobImage: (jobId: string) => handleDeleteJobImage(ctx, jobId),
    handleGetJob: (jobId: string) => handleGetJob(ctx, jobId),
    handleCancelJob: (jobId: string) => handleCancelJob(ctx, jobId),
    handleImageUpload: (jobId: string, request: Request) => handleImageUpload(ctx, jobId, request),
    handleSubmitChat: (request, userId) => handleSubmitChat(ctx, request, userId),
    handleGetChat: (chatId: string) => handleGetChat(ctx, chatId),
    handleCancelChat: (chatId: string) => handleCancelChat(ctx, chatId),
    handleSubmitTalk: (request, userId) => handleSubmitTalk(ctx, request, userId),
    handleGetTalk: (talkId: string) => handleGetTalk(ctx, talkId),
    handleCancelTalk: (talkId: string) => handleCancelTalk(ctx, talkId),
    handleDeleteTalkAudio: (talkId: string) => handleDeleteTalkAudio(ctx, talkId),
    handleAudioUpload: (talkId: string, request: Request) => handleAudioUpload(ctx, talkId, request),
    handleSubmitAsr: (request, userId) => handleSubmitAsr(ctx, request, userId),
    handleGetAsr: (asrId: string) => handleGetAsr(ctx, asrId),
    handleCancelAsr: (asrId: string) => handleCancelAsr(ctx, asrId),
    handleSubmitEmbed: (request, userId) => handleSubmitEmbed(ctx, request, userId),
    handleGetEmbed: (embedId: string) => handleGetEmbed(ctx, embedId),
    handleCancelEmbed: (embedId: string) => handleCancelEmbed(ctx, embedId),
    handleSubmitOcr: (request, userId) => handleSubmitOcr(ctx, request, userId),
    handleGetOcr: (ocrId: string) => handleGetOcr(ctx, ocrId),
    handleCancelOcr: (ocrId: string) => handleCancelOcr(ctx, ocrId),
    handleSubmitTool: (request, userId) => handleSubmitTool(ctx, request, userId),
    handleGetTool: (toolId: string) => handleGetTool(ctx, toolId),
    handleCancelTool: (toolId: string) => handleCancelTool(ctx, toolId),
    handleToolUpload: (toolId: string, artifactName: string, request: Request) =>
      handleToolUpload(ctx, toolId, artifactName, request),
    handleCreateGraphJob: (request, userId, origin) => handleCreateGraphJob(ctx, request, userId, origin),
    handleUploadGraphAsset: (jobId, digest, request) => handleUploadGraphAsset(ctx, jobId, digest, request),
    handleCommitGraphJob: (jobId) => handleCommitGraphJob(ctx, jobId),
    handleGetGraphJob: (jobId) => handleGetGraphJob(ctx, jobId),
    handleListGraphJobs: (limit) => handleListGraphJobs(ctx, limit),
    handlePreflightGraphJob: (request) => handlePreflightGraphJob(ctx, request),
    handleGraphEvents: (jobId) => handleGraphEvents(ctx, jobId),
    handleCancelGraphJob: (jobId) => handleCancelGraphJob(ctx, jobId),
    handleRetryGraphJob: (jobId) => handleRetryGraphJob(ctx, jobId),
    handleGraphEvent: (message) => handleGraphEvent(ctx, message),
    handleGraphResult: (message) => handleGraphResult(ctx, message),
    handleGraphError: (message) => handleGraphError(ctx, message),
    handleGraphNodeRequest: (jobId, token, action, request) =>
      handleGraphNodeRequest(ctx, jobId, token, action, request),
    handleGetGraphRunManifest: (jobId) => handleGetGraphRunManifest(ctx, jobId),
    handleGetGraphArtifact: (jobId, name) => handleGetGraphArtifact(ctx, jobId, name),
    handleGraphCapabilities: async () => Response.json(await graphFleetCapabilities(ctx)),
    handleGraphTelemetry: () => handleGraphTelemetry(ctx),
  };
}
